// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4YvS70dnOgKcBaSisYsld3tbU19cNYqU',
    appId: '1:448944707828:web:d8a5274300a222cd3aa6a1',
    messagingSenderId: '448944707828',
    projectId: 'ryden12',
    authDomain: 'ryden12.firebaseapp.com',
    storageBucket: 'ryden12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTaep0b5hD6rRbJrDse0twKSy8rmSYiM',
    appId: '1:448944707828:android:d8c54bdc3b677e7c3aa6a1',
    messagingSenderId: '448944707828',
    projectId: 'ryden12',
    storageBucket: 'ryden12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAmE8UuhGn7MrcuXz88aMVjLdT5bx7HM8',
    appId: '1:448944707828:ios:0b7546ce6231963b3aa6a1',
    messagingSenderId: '448944707828',
    projectId: 'ryden12',
    storageBucket: 'ryden12.firebasestorage.app',
    iosBundleId: 'com.example.rydenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAmE8UuhGn7MrcuXz88aMVjLdT5bx7HM8',
    appId: '1:448944707828:ios:0b7546ce6231963b3aa6a1',
    messagingSenderId: '448944707828',
    projectId: 'ryden12',
    storageBucket: 'ryden12.firebasestorage.app',
    iosBundleId: 'com.example.rydenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4YvS70dnOgKcBaSisYsld3tbU19cNYqU',
    appId: '1:448944707828:web:dc0934c9f243886d3aa6a1',
    messagingSenderId: '448944707828',
    projectId: 'ryden12',
    authDomain: 'ryden12.firebaseapp.com',
    storageBucket: 'ryden12.firebasestorage.app',
  );
}
